### ISSUE TITLE
Bug: Sleep table with wrong dates for sleep onset and offset

### ISSUE THREAD

**Issue by nathaliaesper** [childmindresearch/app-actigraphy#45]
### Description

The sleep table displayed under the graph indicates a sleep onset and offset that does not correspond to any visual data.

### Steps to Reproduce

Run the command: `docker run -p 127.0.0.1:8051:8051 --volume ~/Documents/TEMP/actigraphy_tests/subjects:/data --volume 'pwd'/assets:/app/assets cmidair/actigraphy:latest`

Sample: NDARBB118UDB on day 2 - Friday 18 May 2018.

### Expected Results

As a result, we don't expect to see a value for 'sleep duration' because we do not have a valid sleep episode for this day.

### Actual Results

Here is a screenshot of the issue:

![Screen Shot 2024-01-15 at 7 15 00 PM](https://github.com/cmi-dair/app-actigraphy/assets/9296447/d0120ee9-8697-4ff9-b6a5-597bb23cc3a8)

### Additional Notes

Looking at GGIR outputs, this day has a sleep window annotated by their algorithm. I think the problem here is that both dates on the sleep table are wrong. Since the sleep episode occurred after midnight, the table should be displaying 19 May 2019 as the onset and offset instead of 18 May 2018. Probably, this is the reason not to see the red shading.

You can find the data to reproduce this bug on ACCESS: `/ocean/projects/med220004p/shared/data_derived/Actigraphy/data_to_reproduce_bugs`

**Comment by nathaliaesper** [comment]
Here is another example with the incorrect dates on the sleep table. The dates are wrong, but the time is correct.

![Screen Shot 2024-01-15 at 7 38 13 PM](https://github.com/cmi-dair/app-actigraphy/assets/9296447/3ad92e4c-0302-43d5-bc35-a650aaa7f303)

**Comment by ReinderVosDeWael** [comment]
These are two separate bugs:

- [ ] Onset times between 00:00 - 12:00 should always be on the second day (2nd example).
- [ ] A wrong time seems to be imported in some cases (first example)

**Comment by ReinderVosDeWael** [comment]
Closing as the faulty timestamp is due to GGIR, not the Actigraphy application.
