### ISSUE TITLE
Bug: data_cleaning file is not following GGIR's format

### ISSUE THREAD

**Issue by nathaliaesper** [childmindresearch/app-actigraphy#58]
### Description

The data_cleaning file contains all the days the user marked as "are >2 hours of data missing between 8PM to 8AM?". This will clean the data and not consider those nights for the sleep statistics.

### Steps to Reproduce

1. Run the command: `docker run -p 127.0.0.1:8051:8051 --volume ~/Documents/TEMP/actigraphy_tests/processed_data:/data --volume ~/Documents/Github_repositories/app-actigraphy/assets:/app/assets cmidair/actigraphy:latest`
2. Select a participant (any participant)

### Expected Results

We expect, as a result, a .csv file following GGIR standards (link [here](https://cran.r-project.org/web/packages/GGIR/vignettes/GGIR.html#Data_cleaning_file)). The data_cleaning file should look like this:
![Screen Shot 2024-01-29 at 12 24 53 PM](https://github.com/childmindresearch/app-actigraphy/assets/9296447/f144ffcb-5bc9-495b-85ac-4b9c0d92d313)
The column night_part4 will contain all the nights with invalid sleep data (defined by the user).

### Actual Results

Right now, the app is creating a .csv file with a binary vector.
<img width="433" alt="Screen Shot 2024-01-29 at 12 27 47 PM" src="https://github.com/childmindresearch/app-actigraphy/assets/9296447/a43f96eb-1f49-46d8-963f-77f6bd4271d5">

**Comment by ReinderVosDeWael** [comment]
<img width="430" alt="Screenshot 2024-01-29 at 3 16 47 PM" src="https://github.com/childmindresearch/app-actigraphy/assets/22434281/749aa122-82ec-4348-b14e-c5728c401dd5">

@nathaliaesper can you confirm this is correct: night_part4 is a list of ***1-indexed*** space separated integers? In other words this would exclude nights 2, 3, 4, and 15?

**Comment by nathaliaesper** [comment]
Yes, that's correct.
