### ISSUE TITLE
Bug: Memory Leak Leading to Container Shutdown

### ISSUE THREAD

**Issue by kimit0310** [childmindresearch/app-actigraphy#88]
### Description

The Docker container hosting our application may have a memory leak issue, leading to RAM overload and eventual container shutdown. This issue occurs consistently after processing data for about three participants, where the RAM usage trends upward without release, ultimately causing the container to crash.

**Environment**:
Docker Version: Docker version 27.1.1, build 6312585
Base Image: cmidair/actigraphy:latest
Host OS: macOS 14.5

**Logs and Screenshots**:

- Logs: Please find attached log from the container, which includes details from both crashes.
- Screenshots: Below are screenshots showing the container resource usage over time. You can observe the upward trend and the peaks corresponding to the loading of each participant's data.
  - Crash1: This screenshot shows the container's resource usage statistics up to just before the first crash.
  - Crash_2_0 to Crash_2_4: These screenshots show the container's resource usage statistics for the second crash, presented in a temporally sequential manner.

<img width="1624" alt="crash1" src="https://github.com/user-attachments/assets/01942f17-9942-4f1e-ab61-37b652634223">
<img width="1624" alt="crash2_0" src="https://github.com/user-attachments/assets/796a1f18-b9cb-4dce-bf46-0134e64689bd">
<img width="1580" alt="crash2_1" src="https://github.com/user-attachments/assets/e3e12ce5-3826-4da5-866a-0473f562ca79">
<img width="1624" alt="crash2_2" src="https://github.com/user-attachments/assets/26e89650-dffa-4afc-922c-410682197849">
<img width="1624" alt="crash2_3" src="https://github.com/user-attachments/assets/f0181f21-453e-4269-af12-8545dc94dc8b">
<img width="1624" alt="crash2_4" src="https://github.com/user-attachments/assets/0184c931-b19c-4ef2-9230-1f732e384c67">
[logs.txt](https://github.com/user-attachments/files/16664023/logs.txt)

### Steps to Reproduce

1. Start the Docker container using the following command:
`docker run -p 127.0.0.1:8051:8051 --volume PATH_TO_DATA:/data --volume `pwd`/assets:/app/assets cmidair/actigraphy:latest`
2. Load a participant data by selecting it from the drop-down menu and pressing Load Files
3. Progress through each night for the participant until the last night for each participant
4. Continue steps 2 and 3 while monitoring the RAM usage
5. Around the end of 3rd participant or when 4th participant is loaded, observe the RAM usage and container behavior

### Expected Results

RAM usage should stabilize or decrease after processing each night's data or when transitioning between participants. The container should continue to function without interruption or significant slowdown.

### Actual Results

- RAM usage trends upward continuously during the process.
- Noticeable peaks in RAM usage occur when loading each participant.
- The container crashes after processing data for about three participants.

### Additional Notes

- The application works as expected for the first few participants but fails consistently after three participants.
- The issue might be related to memory management, as the data is not unloaded from RAM after processing each night’s data.

**Comment by ReinderVosDeWael** [comment]
I think I found the issue; though let me know if it persists for a larger number of subjects. You will experience slower loading times when going back to days you've loaded before once the fix is merged.
